const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let browser;
const server=http.createServer((req,res)=>{const name=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!name.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(name,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.webp')?'image/webp':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});const page=await browser.newPage({viewport:{width:1000,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});await page.goto('http://127.0.0.1:'+server.address().port+'/warehouse-full-preview.html');await page.waitForFunction(()=>!!window.fullWarehouse?.world.scene.getObjectByName('warehouse-lift'));
const result=await page.evaluate(()=>{
 const current=Warehouse3D,rect=WarehouseLayout.floor.rects.find(r=>r.label==='リフト'),world=fullWarehouse.world,lift=world.scene.getObjectByName('warehouse-lift');lift.updateMatrixWorld(true);
 const bounds=new THREE.Box3(),instance=new THREE.Matrix4();lift.traverse(o=>{if(!o.geometry)return;o.geometry.computeBoundingBox();if(o.isInstancedMesh){for(let i=0;i<o.count;i++){o.getMatrixAt(i,instance);const m=new THREE.Matrix4().multiplyMatrices(o.matrixWorld,instance);bounds.union(o.geometry.boundingBox.clone().applyMatrix4(m));}}else bounds.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));});
 const p=fullWarehouse.getPosition(),nav=fullWarehouse.nav;return {count:world.scene.children.filter(o=>o.name==='warehouse-lift').length,bounds:[bounds.min.toArray(),bounds.max.toArray()],rect,blocked:nav.blocked((rect.x+rect.w/2)*2,(rect.y+rect.h/2)*2),free:!nav.blocked(p.x,p.z),zoneCount:world.pickZones.filter(o=>o.userData.rect.id===rect.id).length,shelfDirection:current.shelfSettings.direction,storage:localStorage.length};
});assert.equal(result.count,1);assert.equal(result.zoneCount,1);assert(result.blocked&&result.free);assert.equal(result.shelfDirection,'z');assert.equal(result.storage,0);const [min,max]=result.bounds,r=result.rect;assert(min[0]>=r.x*2&&max[0]<=(r.x+r.w)*2);assert(min[2]>=r.y*2&&max[2]<=(r.y+r.h)*2);assert(min[1]>=0&&min[1]<.06&&max[1]<9.6,'lift should be grounded');
if(process.env.BASELINE_WORLD){const baseline=fs.readFileSync(process.env.BASELINE_WORLD,'utf8');const comparison=await page.evaluate(code=>{
 const current=Warehouse3D,db={maps:{floors:[WarehouseLayout.floor]},spots:{}},r=WarehouseLayout.floor.rects.find(r=>r.label==='リフト'),before=JSON.stringify(db);const ignore=(x,z)=>x>=r.x*2-.02&&x<=(r.x+r.w)*2+.02&&z>=r.y*2-.02&&z<=(r.y+r.h)*2+.02;
 function snapshot(world){const records=[];function material(m){return [m.type,m.color?.getHex(),m.roughness,m.metalness,m.opacity,m.map?.image?.src||''];}
 world.scene.traverse(o=>{for(let p=o;p;p=p.parent)if(p.name==='warehouse-lift')return;const round=v=>Number(v.toFixed(5));if(o.isInstancedMesh){const matrix=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,matrix);if(!ignore(matrix.elements[12],matrix.elements[14]))records.push(JSON.stringify(['instance',o.geometry.type,material(o.material),matrix.elements.map(round)]));}}else if(o.isMesh||o.isSprite||o.isLight){if(!ignore(o.position.x,o.position.z))records.push(JSON.stringify([o.type,o.geometry?.type,o.geometry?.parameters,o.material?material(o.material):null,o.position.toArray().map(round),o.rotation.toArray(),o.scale.toArray(),o.color?.getHex(),o.intensity,o.distance]));}});return records.sort();}
 const updated=current.createWorld(db,0,{walk:true}),after=snapshot(updated),blocks=JSON.stringify(updated.blockers);current.dispose(updated.scene);(0,eval)(code);const original=Warehouse3D.createWorld(db,0,{walk:true}),prior=snapshot(original),sameBlocks=blocks===JSON.stringify(original.blockers);Warehouse3D.dispose(original.scene);window.Warehouse3D=current;return {equal:JSON.stringify(prior)===JSON.stringify(after),count:prior.length,sameBlocks,sameData:before===JSON.stringify(db)};
},baseline);assert(comparison.equal,JSON.stringify(comparison));assert(comparison.sameBlocks&&comparison.sameData);console.log('PASS: outside lift area unchanged, collision and data preserved',comparison.count);}
await page.evaluate(()=>{fullWarehouse.destroy();window.fullWarehouse=WarehouseWalk.create(document.getElementById('stage'),{maps:{cur:0,floors:[WarehouseLayout.floor]},spots:{}},0,{position:{x:12,z:14,yaw:Math.atan2(10,-1),pitch:-.16}});});await page.addStyleTag({content:'header,#viewpoints,#controls,#miniBox,#message,.hint{display:none!important}'});await page.waitForTimeout(300);if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'ver54-lift.png')});assert.deepEqual(errors,[]);console.log('PASS: lift geometry inside registered region; latest vertical shelves preserved; no errors');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
