const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..');let browser;
const server=http.createServer((req,res)=>{const name=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!name.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(name,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.webp')?'image/webp':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});const page=await browser.newPage({viewport:{width:1000,height:780}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))errors.push(m.text());});await page.goto('http://127.0.0.1:'+server.address().port+'/warehouse-full-preview.html');await page.waitForFunction(()=>!!window.fullWarehouse?.world.scene.getObjectByName('office-workstation'));
const state=await page.evaluate(()=>{const world=fullWarehouse.world,desk=world.office.desk,r=WarehouseLayout.floor.rects,nav=fullWarehouse.nav,p=fullWarehouse.getPosition(),reachable=nav.flood(nav.nearest(p.x,p.z));const a=[desk.x-desk.w/2-.04,.25,desk.x+desk.w/2+.04,desk.z+desk.d/2+.1],chair=[desk.x-.84,desk.z+2.08-.84,desk.x+.84,desk.z+2.08+.84];const overlap=(box,rect)=>box[0]<(rect.x+rect.w)*2&&box[2]>rect.x*2&&box[1]<(rect.y+rect.h)*2&&box[3]>rect.y*2;return {windows:world.scene.getObjectByName('warehouse-office').children.filter(o=>o.name==='office-window').length,acs:world.scene.getObjectByName('warehouse-office').children.filter(o=>o.name==='office-air-conditioner').length,noOverlap:r.every(rect=>!overlap(a,rect)&&!overlap(chair,rect)),deskBlocked:nav.blocked(desk.x,desk.z),frontReachable:!!reachable[nav.nearest(desk.x,desk.z+3.4)],viewpointsReachable:WarehouseLayout.viewpoints.every(q=>reachable[nav.nearest(q.x,q.z)]),shelfDirection:Warehouse3D.shelfSettings.direction,lift:!!world.scene.getObjectByName('warehouse-lift'),storage:localStorage.length};});assert(state.windows>=2);assert.equal(state.acs,2);assert(state.noOverlap&&state.deskBlocked&&state.frontReachable&&state.viewpointsReachable);assert.equal(state.shelfDirection,'z');assert(state.lift);assert.equal(state.storage,0);
const safe=await page.evaluate(()=>{const f=WarehouseLayout.floor;return {other:Warehouse3D.officeLayout({cols:20,rows:20,rects:[{x:3,y:0,w:10,h:3,label:'資材'}]}),full:Warehouse3D.officeLayout({cols:20,rows:20,rects:[{x:0,y:0,w:20,h:4,label:'PC'}]})};});assert.equal(safe.other,null);assert.equal(safe.full.desk,null);
if(process.env.BASELINE_WORLD){const code=fs.readFileSync(process.env.BASELINE_WORLD,'utf8');const check=await page.evaluate(code=>{const current=Warehouse3D,db={maps:{floors:[WarehouseLayout.floor]},spots:{}},before=JSON.stringify(db);
function snapshot(world){const rows=[];function material(m){return [m.type,m.color?.getHex(),m.roughness,m.metalness,m.opacity,m.map?.image?.src||''];}world.scene.traverse(o=>{for(let p=o;p;p=p.parent)if(p.name==='warehouse-office')return;const round=v=>Number(v.toFixed(5));if(o.isInstancedMesh){const a=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,a);rows.push(JSON.stringify(['i',o.geometry.type,material(o.material),a.elements.map(round)]));}}else if(o.isMesh||o.isSprite||o.isLight)rows.push(JSON.stringify([o.type,o.geometry?.type,o.geometry?.parameters,o.material?material(o.material):null,o.position.toArray().map(round),o.rotation.toArray(),o.scale.toArray(),o.color?.getHex(),o.intensity,o.distance]));});return rows.map(row=>JSON.stringify(JSON.parse(row),(key,value)=>key==='uuid'?undefined:value)).sort();}
const updated=current.createWorld(db,0,{walk:true}),after=snapshot(updated),blocks=updated.blockers;current.dispose(updated.scene);(0,eval)(code);const original=Warehouse3D.createWorld(db,0,{walk:true}),prior=snapshot(original),priorBlocks=original.blockers;Warehouse3D.dispose(original.scene);window.Warehouse3D=current;return {same:JSON.stringify(prior)===JSON.stringify(after),count:prior.length,oldBlocksKept:JSON.stringify(blocks.slice(0,priorBlocks.length))===JSON.stringify(priorBlocks),dataKept:before===JSON.stringify(db)};},code);assert(check.same,JSON.stringify(check));assert(check.oldBlocksKept&&check.dataKept);console.log('PASS: all original geometry, lighting, blockers and data retained',check.count);}
await page.evaluate(()=>{const target=fullWarehouse.world.office.desk;fullWarehouse.destroy();window.fullWarehouse=WarehouseWalk.create(document.getElementById('stage'),{maps:{cur:0,floors:[WarehouseLayout.floor]},spots:{}},0,{position:{x:target.x,z:9,yaw:0,pitch:-.12}});});await page.addStyleTag({content:'header,#viewpoints,#controls,#miniBox,#message,.hint{display:none!important}'});await page.waitForTimeout(300);if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'ver55-office.png')});assert.deepEqual(errors,[]);console.log('PASS: workstation, windows, AC, clear placement and routes, safe full-floor fallback, no errors');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
