const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),shots=process.env.SCREENSHOT_DIR;let browser;
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+req.url.split('?')[0]);if(!p.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(p,(e,d)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'text/html');res.end(d);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});
 const page=await browser.newPage({viewport:{width:412,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());const url='http://127.0.0.1:'+server.address().port;
 await page.goto(url+'/index.html');
 const fixture={name:'検証フロア',cols:24,rows:24,annex:false,floor:'green',floorTiles:{'3,4':'concrete'},rects:[{id:1,x:4,y:1,w:12,h:4,label:'資材'},{id:2,x:4,y:5,w:4,h:1,pal:true},{id:3,x:10,y:5,w:6,h:1,pal:true},{id:4,x:0,y:10,w:1,h:2,type:'door',label:'扉'},{id:5,x:19,y:1,w:2,h:3,type:'pcdesk',label:'PC机',back:'west'},{id:6,x:12,y:14,w:10,h:8,label:'棚番の品'}]};
 await page.evaluate(f=>{const db=JSON.parse(localStorage.getItem('pickingDB_v1')||'{}');db.maps={cur:0,floors:[f,{name:'別フロア',cols:10,rows:10,rects:[],floorTiles:{'1,1':'green'},annex:false}]};db.spots={C00004765:{cells:[{f:0,x:4,y:5,w:2,h:1,s:'r'}]}};db.ceil={C00004765:[{n:'36-1',s:'r',t:123}]};db.ver57Sentinel={keep:'all-data'};localStorage.setItem('pickingDB_v1',JSON.stringify(db));},fixture);await page.reload();
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('pickingDB_v1')));const before=await read();
 await page.locator('#bnMap').click();await page.locator('#mpAddCartBay').click();let saved=await read(),cart=saved.maps.floors[0].rects.find(r=>r.type==='cartbay');assert(cart);const original={...cart};
 const rect=page.locator('.mp-rect.t-cartbay'),bounds=await rect.boundingBox(),frame=await page.locator('#mpFrame').boundingBox();
 await page.mouse.move(bounds.x+bounds.width*.4,bounds.y+bounds.height*.4);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width*.4+frame.width/24*2,bounds.y+bounds.height*.4+frame.height/24,{steps:6});await page.mouse.up();
 saved=await read();cart=saved.maps.floors[0].rects.find(r=>r.type==='cartbay');assert.equal(cart.x,original.x+2);assert.equal(cart.y,original.y+1);
 await page.locator('#mpCartSize').click();await page.locator('#mpCartSizeDialog input[name=w]').fill('5');await page.locator('#mpCartSizeDialog input[name=h]').fill('3');await page.locator('#mpCartSizeDialog button[type=submit]').click();await page.locator('#mpRot').click();
 cart=(await read()).maps.floors[0].rects.find(r=>r.type==='cartbay');assert.deepEqual([cart.w,cart.h,cart.cartTurn],[3,5,1]);
 await page.locator('#mpDup').click();saved=await read();assert.equal(saved.maps.floors[0].rects.filter(r=>r.type==='cartbay').length,2);await page.locator('#mpDel').click();assert.equal((await read()).maps.floors[0].rects.filter(r=>r.type==='cartbay').length,1);
 // Refresh deselects. Room settings change only the one room property.
 await page.reload();await page.locator('#bnMap').click();await page.locator('#mpMaterialRoom').click();
 await page.locator('#mpMaterialRoomDialog input').evaluate(e=>{e.value='1';e.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#mpMaterialRoomDialog button[type=submit]').click();await page.reload();saved=await read();assert.equal(saved.maps.floors[0].rects[0].materialRoom.doorOffset,1);
 assert.deepEqual(saved.maps.floors[0].rects.slice(1,fixture.rects.length),before.maps.floors[0].rects.slice(1));assert.deepEqual(saved.maps.floors[1],before.maps.floors[1]);assert.deepEqual(saved.spots,before.spots);assert.deepEqual(saved.ceil,before.ceil);assert.deepEqual(saved.maps.floors[0].floorTiles,before.maps.floors[0].floorTiles);assert.deepEqual(saved.ver57Sentinel,before.ver57Sentinel);
 await page.addScriptTag({url:url+'/vendor/three-r128.min.js'});await page.evaluate(()=>WarehouseMaterials.load());
 const check=await page.evaluate(()=>{
  const db=JSON.parse(localStorage.getItem('pickingDB_v1')),before=JSON.stringify(db),f=db.maps.floors[0],world=Warehouse3D.createWorld(db,0,{walk:true}),cart=f.rects.find(r=>r.type==='cartbay'),nav=WarehouseWalk.navigation(world.W,world.D,world.blockers),layout=WarehouseV57.cartLayout(cart);
  world.scene.updateMatrixWorld(true);const group=world.scene.getObjectByName('cart-bay'),bounds=new THREE.Box3();group.traverse(o=>{if(!o.isInstancedMesh)return;o.geometry.computeBoundingBox();for(let i=0;i<o.count;i++){const m=new THREE.Matrix4();o.getMatrixAt(i,m);bounds.union(o.geometry.boundingBox.clone().applyMatrix4(m.premultiply(o.matrixWorld)));}});
  const result={dataSame:before===JSON.stringify(db),count:group.userData.cartCount,inside:bounds.min.x>=cart.x*2&&bounds.max.x<=(cart.x+cart.w)*2&&bounds.min.z>=cart.y*2&&bounds.max.z<=(cart.y+cart.h)*2,blocked:nav.blocked((cart.x+cart.w/2)*2,(cart.y+cart.h/2)*2),roomFloor:!!world.scene.getObjectByName('material-room-floor'),roomBlocked:nav.blocked(12,5),sign:!!world.scene.getObjectByName('extinguisher-sign')};
  const auto=WarehouseV57.materialRoomLayout({...f.rects[0],materialRoom:undefined},f);result.gapAligned=auto.doorX>=16&&auto.doorX+auto.doorWidth<=20;
  result.fitAll=[];for(let w=1;w<=7;w++)for(let h=1;h<=7;h++)for(let turn=0;turn<4;turn++){const r={type:'cartbay',x:0,y:0,w,h,cartTurn:turn},a=WarehouseV57.cartLayout(r);result.fitAll.push(a.carts.every(c=>{const hw=(turn%2?1.72:3.32)*c.scale/2,hd=(turn%2?3.32:1.72)*c.scale/2;return c.x-hw>=0&&c.x+hw<=w*2&&c.z-hd>=0&&c.z+hd<=h*2;}));}
  const doorRects=[{x:8,y:0,w:2,h:1},{x:23,y:8,w:1,h:2},{x:8,y:23,w:2,h:1},{x:0,y:8,w:1,h:2}];result.left=doorRects.map(r=>{const g=WarehouseV57.createExtinguishers(THREE,r,48,48),sign=g.getObjectByName('extinguisher-sign');g.updateMatrixWorld(true);const p=sign.getWorldPosition(new THREE.Vector3()),a=WarehouseV57.doorAnchor(r,48,48),dx=p.x-a.x,dz=p.z-a.z;Warehouse3D.dispose(g);return dx*Math.cos(a.angle)-dz*Math.sin(a.angle)<0;});
  Warehouse3D.dispose(world.scene);return result;
 });
 assert(check.dataSame&&check.inside&&check.blocked&&check.roomFloor&&check.roomBlocked&&check.sign&&check.gapAligned&&check.fitAll.every(Boolean)&&check.left.every(Boolean),JSON.stringify(check));
 await page.locator('#bnMap').click();await page.locator('#mpWalk').click();await page.waitForFunction(()=>document.querySelector('#wkStage canvas'));await page.locator('#wkWide').click();assert.equal(await page.locator('#wkWide').getAttribute('aria-pressed'),'true');if(shots)await page.screenshot({path:path.join(shots,'mobile-wide.png')});await page.locator('#wkWide').click();assert.equal(await page.locator('#wkWide').getAttribute('aria-pressed'),'false');
 const fov=await page.evaluate(()=>{const stage=document.createElement('div');stage.style='width:400px;height:400px';document.body.append(stage);const db={maps:{floors:[{cols:10,rows:10,annex:false,rects:[]}]},spots:{}},w=WarehouseWalk.create(stage,db,0),values=[w.cam.fov];w.setWide(true);values.push(w.cam.fov);w.setWide(false);values.push(w.cam.fov);w.destroy();stage.remove();return values;});assert.deepEqual(fov,[60,95,60]);
 assert.deepEqual(errors,[]);console.log('PASS ver57: cart add/drag/size/rotation/duplicate/delete, persistence, room gap and slider, 196 layouts, 4 door fronts, blockers, FOV 60/95/60, existing records preserved.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
