const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let browser;const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+req.url.split('?')[0]);if(!p.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(p,(e,d)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'text/html');res.end(d);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:412,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());const url='http://127.0.0.1:'+server.address().port;
await page.goto(url+'/index.html');await page.evaluate(()=>{const db=JSON.parse(localStorage.getItem('pickingDB_v1')||'{}');db.maps={cur:0,floors:[{name:'黄線検証',cols:20,rows:20,annex:false,floor:'green',floorTiles:{'2,2':'concrete'},rects:[{id:1,x:0,y:8,w:1,h:2,type:'door',label:'扉'},{id:2,x:0,y:2,w:2,h:3,label:'リフト'},{id:3,x:15,y:1,w:2,h:3,type:'pcdesk',back:'west'}]},{name:'2階',cols:10,rows:10,rects:[]}]};db.spots={C001:{cells:[{f:0,x:5,y:5,w:2,h:2,s:'r'}]}};db.ceil={C001:[{n:5,s:'r'}]};db.sentinel='keep';localStorage.setItem('pickingDB_v1',JSON.stringify(db));});await page.reload();const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('pickingDB_v1'))),before=await read();
await page.locator('#bnMap').click();await page.locator('#mpAddYellowLine').click();let db=await read(),r=db.maps.floors[0].rects.find(r=>r.type==='yellowline');assert.deepEqual([r.w,r.h],[4,3]);const original={...r};const b=await page.locator('.t-yellowline .mp-line-edge.top').boundingBox(),f=await page.locator('#mpFrame').boundingBox();await page.mouse.move(b.x+b.width*.4,b.y+b.height*.4);await page.mouse.down();await page.mouse.move(b.x+b.width*.4+f.width/20,b.y+b.height*.4+f.height/20,{steps:5});await page.mouse.up();r=(await read()).maps.floors[0].rects.find(r=>r.type==='yellowline');assert.equal(r.x,original.x+1);assert.equal(r.y,original.y+1);
await page.locator('#mpCartSize').click();assert.equal(await page.locator('#mpCartSizeDialog h3').textContent(),'黄線枠の寸法');await page.locator('#mpCartSizeDialog input[name=w]').fill('3');await page.locator('#mpCartSizeDialog input[name=h]').fill('4');await page.locator('#mpCartSizeDialog button[type=submit]').click();await page.locator('#mpRot').click();r=(await read()).maps.floors[0].rects.find(r=>r.type==='yellowline');assert.deepEqual([r.w,r.h],[4,3]);await page.locator('#mpDup').click();assert.equal((await read()).maps.floors[0].rects.filter(r=>r.type==='yellowline').length,2);await page.waitForTimeout(1250);await page.locator('#mpDel').click();assert.equal((await read()).maps.floors[0].rects.filter(r=>r.type==='yellowline').length,1);await page.locator('#mpUndo').click();assert.equal((await read()).maps.floors[0].rects.filter(r=>r.type==='yellowline').length,2);await page.locator('#mpRedo').click();assert.equal((await read()).maps.floors[0].rects.filter(r=>r.type==='yellowline').length,1);
await page.reload();db=await read();assert.equal(db.maps.floors[0].rects.filter(r=>r.type==='yellowline').length,1);assert.deepEqual(db.maps.floors[0].rects.slice(0,3),before.maps.floors[0].rects);assert.deepEqual(db.maps.floors[0].floorTiles,before.maps.floors[0].floorTiles);assert.deepEqual(db.maps.floors[1],before.maps.floors[1]);assert.deepEqual(db.spots,before.spots);assert.deepEqual(db.ceil,before.ceil);assert.equal(db.sentinel,'keep');
await page.addScriptTag({url:url+'/vendor/three-r128.min.js'});await page.evaluate(()=>WarehouseMaterials.load());const render=await page.evaluate(()=>{const f={cols:20,rows:20,annex:false,rects:[]},db={maps:{floors:[f]},spots:{}},before=Warehouse3D.createWorld(db,0,{walk:true}),count=w=>{let n=0;w.scene.traverse(o=>{if(o.isInstancedMesh)n+=o.count;});return n;},n=count(before);f.rects.push({id:7,type:'yellowline',label:'黄線',x:2,y:2,w:4,h:2});const saved=JSON.stringify(db),after=Warehouse3D.createWorld(db,0,{walk:true}),nav=WarehouseWalk.navigation(after.W,after.D,after.blockers),result={dataSame:saved===JSON.stringify(db),extra:count(after)-n,blockersSame:JSON.stringify(before.blockers)===JSON.stringify(after.blockers),passable:!nav.blocked(8,6),noCart:!after.scene.getObjectByName('cart-bay'),noHit:after.pickZones.length===before.pickZones.length};Warehouse3D.dispose(before.scene);Warehouse3D.dispose(after.scene);return result;});assert(render.dataSame&&render.extra===4&&render.blockersSame&&render.passable&&render.noCart&&render.noHit,JSON.stringify(render));
// Legacy areas keep their outline by default. Toggling participates in the existing Undo history.
await page.locator('#bnMap').click();await page.locator('.mp-rect[data-id="2"]').click();
assert.equal(await page.locator('#mpYellowBorder').getAttribute('aria-pressed'),'true');
assert.equal(Object.hasOwn((await read()).maps.floors[0].rects[1],'drawYellowLine'),false);
await page.waitForTimeout(1250);await page.locator('#mpYellowBorder').click();
assert.equal((await read()).maps.floors[0].rects[1].drawYellowLine,false);
await page.locator('#mpUndo').click();assert.equal((await read()).maps.floors[0].rects[1].drawYellowLine,undefined);
await page.locator('#mpRedo').click();assert.equal((await read()).maps.floors[0].rects[1].drawYellowLine,false);
await page.reload();assert.equal((await read()).maps.floors[0].rects[1].drawYellowLine,false);
// A frame around an existing pallet must leave its interior selectable.
await page.evaluate(()=>{const db=JSON.parse(localStorage.getItem('pickingDB_v1'));db.maps.floors[0].rects=[{id:101,type:'yellowline',label:'黄線',x:3,y:3,w:10,h:10},{id:102,label:'パレット',x:5,y:5,w:4,h:4}];localStorage.setItem('pickingDB_v1',JSON.stringify(db));});await page.reload();await page.locator('#bnMap').click();
const pallet=page.locator('.mp-rect[data-id="102"]');await pallet.click();assert(await pallet.evaluate(e=>e.classList.contains('sel')));
await page.locator('.t-yellowline .mp-line-edge.top').click();assert.equal(await page.locator('#mpParts').isVisible(),false);assert.equal(await page.locator('#mpPal').isVisible(),false);
assert.equal(await page.locator('.t-yellowline').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');
const prev=(await read()).maps.floors[0].rects[0],h=await page.locator('.t-yellowline .mp-handle').boundingBox(),frame=await page.locator('#mpFrame').boundingBox();
await page.mouse.move(h.x+h.width*.35,h.y+h.height*.35);await page.mouse.down();await page.mouse.move(h.x+h.width*.35+frame.width/20,h.y+h.height*.35+frame.height/20,{steps:5});await page.mouse.up();
const resized=(await read()).maps.floors[0].rects[0];assert.deepEqual([resized.w,resized.h],[prev.w+1,prev.h+1]);
await page.addScriptTag({url:url+'/vendor/three-r128.min.js'});await page.evaluate(()=>WarehouseMaterials.load());
const checks=await page.evaluate(async()=>{
 const f={cols:20,rows:20,annex:false,rects:[{id:1,x:5,y:5,w:4,h:4,label:'パレット'}]},db={maps:{floors:[f]},spots:{}},create=()=>Warehouse3D.createWorld(db,0,{walk:true}),count=w=>{let n=0;w.scene.traverse(o=>{if(o.isInstancedMesh)n+=o.count;});return n;};
 const normal=create(),n=count(normal),blocks=JSON.stringify(normal.blockers),picks=normal.pickZones.length;
 f.rects[0].drawYellowLine=false;const off=create();
 f.rects.unshift({id:2,type:'yellowline',label:'黄線',x:3,y:3,w:10,h:10});const framed=create();
 f.rects[0].w=15;f.rects[0].h=15;const large=create();
 const geometry=count(off)===n-4&&count(framed)===n&&count(large)===n&&[off,framed,large].every(w=>JSON.stringify(w.blockers)===blocks&&w.pickZones.length===picks);
 [normal,off,framed,large].forEach(w=>Warehouse3D.dispose(w.scene));
 const inferred={cols:20,rows:20,rects:[{id:1,label:'PC',x:4,y:0,w:2,h:2},{id:2,label:'棚番の品',x:10,y:5,w:2,h:2},{id:3,type:'door',x:0,y:3,w:1,h:2},{id:4,x:8,y:18,w:2,h:2}]};
 const infer=()=>JSON.stringify([Warehouse3D.wallFixtureLayout(inferred),Warehouse3D.annexLayout(inferred)]),original=infer();
 inferred.rects.push({type:'yellowline',label:'PC',x:0,y:0,w:20,h:20});const inferSame=infer()===original;
 inferred.rects=inferred.rects.filter(r=>r.label!=='棚番の品');inferred.rects.push({type:'yellowline',label:'棚番の品',x:0,y:0,w:20,h:20});const noAnnex=Warehouse3D.annexLayout(inferred)===null;
 // Sample actual minimap pixels at a clear interior point and an outline point.
 const mini=document.createElement('canvas');mini.width=216;mini.height=216;const stage=document.createElement('div');stage.style.cssText='width:300px;height:200px';document.body.append(stage);
 f.rects=[{type:'yellowline',x:3,y:3,w:10,h:10},{id:1,x:5,y:5,w:4,h:4,label:'パレット'}];
 const walk=WarehouseWalk.create(stage,db,0,{minimap:mini,position:{x:36,z:36}});await new Promise(r=>setTimeout(r,350));
 const ctx=mini.getContext('2d'),m=mini._map,pixel=(x,y)=>Array.from(ctx.getImageData(Math.round(m.ox+x*2*m.k),Math.round(m.oy+y*2*m.k),1,1).data);
 const inner=pixel(4,4),outer=pixel(2,4),edge=pixel(3,4),palletPixel=pixel(6,6);walk.destroy();stage.remove();
 return {geometry,inferSame,noAnnex,inner,outer,edge,palletPixel};
});assert(checks.geometry&&checks.inferSame&&checks.noAnnex,JSON.stringify(checks));assert.deepEqual(checks.inner,checks.outer);assert.deepEqual(checks.edge,[182,162,76,255]);assert.notDeepEqual(checks.palletPixel,checks.inner);
assert.deepEqual(errors,[]);console.log('PASS: yellow frame add/edge drag/handle resize/dimensions/rotate/duplicate/delete/Undo/Redo/reload; toggle default and Undo; interior pallet selection; transparent map/minimap; four line segments only; pallet counts and blockers unchanged; fixtures/annex unchanged; saved data preserved');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
